server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collabeditor
    username: yourUsername
    password: yourPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  websocket:
    enabled: true
